<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="flat_bot">
    <xacro:macro name="flat_bot">

        <link name="base_footprint" />

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
                <material name="grey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>   
                <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${base_mass}"/>
                <xacro:box_inertia m="${base_mass}" x="${base_size_x}" y="${base_size_y}" z="${base_size_z}"/>
            </inertial>
            </link>

            <joint name="fl_wheel_joint" type="fixed">
                <parent link="base_link"/>
                <child link="fl_wheel_link"/>
                <origin xyz="${-wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${-M_PI/2}" />
            </joint>

            <link name="fl_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                
                <mesh filename="$(find r2_description)/meshes/fl_wheel_link.STL" scale="0.6 0.6 0.6" />
                </geometry>
                <material name="darkgrey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>   
                <box size="${wheel_width} ${wheel_radius*2} ${wheel_radius*2}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheel_mass}" />
                <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
            </inertial>
        </link>

        <joint name="fr_wheel_joint" type="fixed">
            <parent link="base_link"/>
            <child link="fr_wheel_link"/>
            <origin xyz="${-wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${M_PI/2}" />
        </joint>

        <link name="fr_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <mesh filename="$(find r2_description)/meshes/fr_wheel_link.STL" scale="0.6 0.6 0.6" />
                </geometry>
                <material name="darkgrey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>   
                <box size="${wheel_width} ${wheel_radius*2} ${wheel_radius*2}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheel_mass}" />
                <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
            </inertial>
            </link>

            <joint name="rl_wheel_joint" type="fixed">
                <parent link="base_link"/>
                <child link="rl_wheel_link"/>
                <origin xyz="${wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${-M_PI/2}" />
            </joint>

            <link name="rl_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <mesh filename="$(find r2_description)/meshes/rl_wheel_link.STL" scale="0.6 0.6 0.6" />
                </geometry>
                <material name="darkgrey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>   
                <box size="${wheel_width} ${wheel_radius*2} ${wheel_radius*2}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheel_mass}" />
                <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
            </inertial>
            </link>

            <joint name="rr_wheel_joint" type="fixed">
                <parent link="base_link"/>
                <child link="rr_wheel_link"/>
                <origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 ${M_PI/2}" />
            </joint>
            <link name="rr_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <mesh filename="$(find r2_description)/meshes/rr_wheel_link.STL" scale="0.6 0.6 0.6" />
                </geometry>
                <material name="darkgrey" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>   
                <box size="${wheel_width} ${wheel_radius*2} ${wheel_radius*2}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <mass value="${wheel_mass}" />
                <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" w="${wheel_width}" />
            </inertial>
        </link>

        <joint name="luna_1_joint" type="fixed">
            <parent link="base_link" />
            <child link="luna_1" />
            <origin xyz="0.22 0.1 0" rpy="0 0 0" />
        </joint>

        <link name="luna_1">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${sensor_mass}"/>
                <xacro:box_inertia m="${sensor_mass}" x="${sensor_size_x}" y="${sensor_size_y}" z="${sensor_size_z}"/>
            </inertial>
            </link>

            <joint name="luna_2_joint" type="fixed">
                <parent link="base_link" />
                <child link="luna_2" />
                <origin xyz="0.22 -0.1 0" rpy="0 0 0" />
            </joint>

            <link name="luna_2">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${sensor_mass}"/>
                <xacro:box_inertia m="${sensor_mass}" x="${sensor_size_x}" y="${sensor_size_y}" z="${sensor_size_z}"/>
            </inertial>
        </link>

        <joint name="luna_3_joint" type="fixed">
            <parent link="base_link" />
            <child link="luna_3" />
            <origin xyz="0.1 -0.2 0" rpy="0 0 ${-M_PI/2}" />
        </joint>

        <link name = "luna_3">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${sensor_mass}"/>
                <xacro:box_inertia m="${sensor_mass}" x="${sensor_size_x}" y="${sensor_size_y}" z="${sensor_size_z}"/>
            </inertial>
        </link>

        <joint name="luna_4_joint" type="fixed">
            <parent link="base_link" />
            <child link="luna_4" />
            <origin xyz="-0.1 -0.2 0" rpy="0 0 ${-M_PI/2}" />
        </joint>

        <link name = "luna_4">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                <box size="${sensor_size_x} ${sensor_size_y} ${sensor_size_z}" />
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${sensor_mass}"/>
                <xacro:box_inertia m="${sensor_mass}" x="${sensor_size_x}" y="${sensor_size_y}" z="${sensor_size_z}"/>
            </inertial>
        </link>

        <!-- IMU LINK AT CENTER OF ROBOT -->
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
        <origin xyz="0 0 0.01" rpy="0 0 0" />
    </joint>
  
  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
      <material name="grey" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.02 0.02 0.02" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="0.100"/>
      <xacro:box_inertia m="0.100" x="0.02" y="0.02" z="0.02"/>
    </inertial>
  </link>
  

    </xacro:macro>
</robot>
