controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController
    
    effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController




effort_controller:
  ros__parameters:
    joints:
      - claw_left_lift
      - claw_right_lift


position_controller:
  ros__parameters:
    joints:
      - claw_left_lift
      - claw_right_lift

    
joint_trajectory_controller:
  ros__parameters:
    joints:
      - lift_base_link
      - claw_left_lift
      - claw_right_lift

    command_interfaces:
      - position
    state_interfaces:
      - position
      # - effort

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      # joint1:
      #   trajectory: 0.05
      #   goal: 0.03

