luna_wall_align:
  ros__parameters:
    linear_x_max: 2.0
    linear_y_max: 2.0
    linear_x_min: -2.0
    linear_y_min: -2.0
    angular_z_max: 1.0
    angular_z_min: -1.0
    kp_linear: 0.05
    ki_linear: 0.0
    kd_linear: 0.0
    kp_angular: 0.08
    ki_angular: 0.0
    kd_angular: 0.0
    # x_goal: 40.0
    # y_goal: 50.0
    silo_1_x: 25.0
    silo_1_y: 200.0
    silo_2_x: 13.0
    silo_2_y: 250.0
    silo_3_x: 32.0
    silo_3_y: 21.0
    silo_4_x: 25.0
    silo_4_y: 300.0
    silo_5_x: 25.0
    silo_5_y: 340.0


