luna_allignment_server:
  ros__parameters:
    linear_x_max: 2.0
    linear_y_max: 2.0
    linear_x_min: -2.0
    linear_y_min: -2.0
    angular_z_max: 3.0
    angular_z_min: -3.0
    kp_linear_x: 0.5
    ki_linear_x: 0.01
    kd_linear_x: 0.00
    kp_linear_y: 0.9
    ki_linear_y: 0.01
    kd_linear_y: 0.00
    kp_angular: 1.4
    ki_angular: 0.1
    kd_angular: 0.0
    silo_1_x: 0.1
    silo_1_y: 3.28
    silo_2_x: 0.1
    silo_2_y: 2.55
    silo_3_x: 0.1
    silo_3_y: 1.76
    silo_4_x: 0.1
    silo_4_y: 1.04
    silo_5_x: 0.1
    silo_5_y: 0.31
  
# quaternion_to_rpy:
#   ros__parameters:

robot_altitude_check:
  ros__parameters:
    pitch_threshold: 3.6                   # Pitch threshold for detecting climb/descent
    noise_threshold: 0.6                # Threshold to consider the pitch stable around 0
    pitch_history_size: 10                # Size of pitch values (tuned for the robot's speed)
    slope_state: False                   # Initial state
    logging: False

silo_deciding_server:
  ros__parameters:
    logging: False

yolo_results:
  ros__parameters:
    deviation: 170
    logging: False  