    maintainer='adyansh04',
robot_altitude_check:
  ros__parameters:
    pitch_threshold: 7.0                   # Pitch threshold for detecting climb/descent
    noise_threshold: 0.6                # Threshold to consider the pitch stable around 0
    pitch_history_size: 10                # Size of pitch values (tuned for the robot's speed)
    slope_state: False                   # Initial state
    logging: False

silo_deciding_server:
  ros__parameters:
    logging: False

yolo_results:
  ros__parameters:
    deviation: 300
    
    logging: False  